### ISSUE TITLE
Discussion & product details sidebar is not loading product details

### ISSUE THREAD

**Issue by karthiksekarnz** [producthunt/producthunt-chrome-extension#16]
I use chrome tab every day to see the gallery but after i visit a product website when I click the PH Bar the sidebar popup with Get and Upvote buttons just show loading animation and only sometimes I had luck to see product details  but most of the time it doesn't work. 

![screen shot 2017-07-27 at 09 53 02](https://user-images.githubusercontent.com/2171885/28645607-5e367b50-72b2-11e7-9dff-4f9016a45219.png)

When I inspected the sidebar it has an iframe src with httpss protocol, but instead if I use https for the url I was able to see product details.

![screenshot- 2017-07-27 10-05-19 1](https://user-images.githubusercontent.com/2171885/28645895-3d311dce-72b3-11e7-9c3f-e664d8b274bc.png)

What I also noticed is when I try to login with twitter using the sidebar popup it doesn't even show any loading animation or any kind of feedback and auth failed as well I think coz I had to login through producthunt.com

This sidebar is very useful to check the product details and quickly upvote.  Can you please look into this issue.

**Comment by Mheaus** [comment]
I've the same problem, because of that I don't upvote anything on product hunt even if I'm checking the new content every day.
So please help.

**Comment by drdataflow** [comment]
I've got this problem too

**Comment by jorgecerda** [comment]
Same here.
