### ISSUE TITLE
Package as extension

### ISSUE THREAD

**Issue by CraigReville** [producthunt/producthunt-chrome-extension#17]
Since the new extension is NOT what the majority of people want, can you please package this extension for installation and allow users to download and Upload Unpacked?

**Comment by tgroutars** [comment]
Hey Craig, we heard you and others and will let you revert to something pretty similar to the old extension, but with the new design. Bear with us for a few weeks 🙏 
Can you tell us what you miss from the old extension and what you don't like in the new one?

**Comment by CraigReville** [comment]
Thank you 🙏

In the old extension, I was "Shopping" for products in a grid pattern and the images were direct reflection of what the product was and the title with short description was to the point. It allowed me to quickly scan and see the latest products with ease and little effort and it made sense because there are no filters or categories I can separate the content by (which would make sense in a list view).

The new layout is a newsfeed / timeline of the products, it requires me to focus more on individual items and be attentive to each product individually as I scroll. I find that I cannot scan the products and  absorb the products in the same way.

I also don't like the Gifs, I find that most of the gifs were gimmicky and did not relevantly demonstrate what the product was.

Furthermore, I don't like the community aspect mixed with the product discovery, it feels like they should be two separate things. The community aspect by itself is fantastic, and I encourage it but not in this manner as my primary goal with the extension is to discover products and not open a new tab to get involved in the community.

I feel that the community would be better suited as an extension that opens a sidebar and sits available on all pages, so you can hit a keyboard shortcut, the sidebar opens and you can instantly create the task and share it or share content directly from any page. Again, this is very different from product discovery and shouldn't be mixed.

I fully understand the thinking, I just didn't like the fact the choice was removed from our hands with no alternative options.

**Comment by tgroutars** [comment]
@CraigReville Thanks a lot for the feedback, it's really helpful 🙏 
Here's a preview of what we want the next version to look like, don't hesitate to add your comments directly on the mockups in InVision https://twitter.com/rrhoover/status/1113794464948969472

I'll close this issue for now, but don't hesitate to reach out via the feedback button in the extension in the future if you have any more feedback :) 

![Screen Shot 2019-04-05 at 11 47 04](https://user-images.githubusercontent.com/7382760/55619223-905a6700-5798-11e9-8862-14b45efdfdd4.png)
