### ISSUE TITLE
Please remove new tab hijacking functionality

### ISSUE THREAD

**Issue by gtallen1187** [producthunt/producthunt-chrome-extension#18]
I'm a big fan of product hunt, and for that reason I'd like to highly recommend that you remove the new tab takeover aspect of the chrome extension.  I don't know if you've checked the reviews recently, but it's been nothing but 1-star reviews for the past half a year.  Please consider removing the new tab portion of the extension, it would make a lot of your users very happy.

**Comment by RStankov** [comment]
Hey, thanks for the feedback.

The single feature of the Chrome extension is to be a new tab. 

Most negative feedback was about missing features from the previous version, performance and UI tweaks. Those issues are addressed or being address.  *(of course performance is something we will always be working on)*
